version: '3.7'

networks:
  payment_system:
    name: payment_system
    driver: bridge


services:
  tomcat:
    container_name: commission-system-tomcat
    image: tomcat:8.5.99
    ports:
      - "8081:8080"
    volumes:
      - ./target/CommissionService-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/CommissionService.war
    networks:
      - payment_system
    depends_on:
      - postgres


  postgres:
    container_name: commission-system-postgres
    image: postgres
    environment:

      POSTGRES_DB: commission_service_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - payment_system
